#!/bin/sh
user=`whoami`
pids=`pgrep -u $user gnome-session`
title=$1
text=$2
timeout=$3
icon=$4
#echo $user 
if [ -z "$title" ]; then
	echo You need to give me a title >&2
	exit 1
fi
if [ -z "$text" ]; then
	text=$title
fi
if [ -z "$timeout" ]; then
	timeout=6000
fi
#echo $pids
#echo "****************" 
for pid in $pids; do
 # find DBUS session bus for this session
	DBUS_SESSION_BUS_ADDRESS=`grep -z DBUS_SESSION_BUS_ADDRESS \
	 /proc/$pid/environ | sed -e 's/DBUS_SESSION_BUS_ADDRESS=//'`
#	echo $DBUS_SESSION_BUS_ADDRESS
 # use it
 
 #icon hack:
if [ -z $icon ]; then
	DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS \
	notify-send -u low -t $timeout "$title" "$text"
	exit
else
	DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS \
	notify-send -u low -t $timeout -i "$icon" "$title" "$text"
	exit
fi
done
exit
